### PR TITLE
(Serialization) Bug fixes, Refactors, Documentation and Features

### PR DESCRIPTION
**Pull request by bradmwalker**
Lots of stuff! Please see the commit messages for details. I didn't test for regression with the noted emac-jedi issue.

### CODE REVIEW

**Comment by graingert** [comment]
@tkf is this maintained anymore?

**Comment by immerrr** [comment]
@graingert the library for the most part just works™, so it fared for quite a while without any maintainership, but @jd-boyd and I have picked it up to modernize it a bit.

**Comment by immerrr** [comment]
@bradmwalker I'm so sorry for such a long wait. Are you still up for getting this in?

**Comment by bradmwalker** [comment]
I'm not. Have fun.

**Comment by jd-boyd** [comment]
I've rebased this off master on this branch: https://github.com/jd-boyd/sexpdata/tree/bradwalker

There are a few failures testing the rebase that I'm working through though.  First, there are issues in adding the dependencies (`singledispatch` and `ordereddict`) based on current python version. It looks like there is supposed to be a better way than:
```python
install_requires = []
if sys.version_info < (3, 4):
    install_requires.append('singledispatch')
if sys.version_info < (2, 7):
    install_requires.append('ordereddict')
```

Currently this is recommended (I think):
```python
install_requires=[
    'singledispatch;python_version<"3.4"',
    'ordereddict;python_version=="2.7"'
]
```

but doing it that was depends on a having a newer version of setuptools than often seems to be present by default.

I'm strongly tempted to drop 2.6 support right now.  I'm also tempted to drop everything before 3.4.  2.7 officially comes to an end next year, and in my opinion python3.2 wasn't worth supporting, and it wasn't until 3.4 that people realized the change.  Personally, I never used any 3.x versions older than 3.5 other than for compatibility testing. I'm leaning toward dropping 2.6, but making 2.7 and 3.3 on up still supported.

**Comment by immerrr** [comment]
Yeah, I agree, 2.6 and 3.1-3.2 can be dropped.

**Pull request closed without merging**
