### PR TITLE
Support formatting output as a tree

### LINKED ISSUE #28: Pretty printing/formatting s-expressions (s-exp sexp) as trees in Python?

### PR DESCRIPTION
**Pull request by mmmspatz**
Fixes #28.

Each set of delimeters (`Brackets` or `Parens`) increases the indent by one level.

```
>>> from sexpdata import *
>>> print(dumps([Symbol('level_0'), Brackets(Symbol('level_1'), 'foo', 'bar'), 'baz'], format_tree=True))
(
  level_0
  [
    level_1
    "foo"
    "bar"
  ]
  "baz"
)
>>>
```

### CODE REVIEW

**Comment by mmmspatz** [comment]
Open to changing the argument names. Maybe `pretty_print` instead of `format_tree`?

**Comment by mmmspatz** [comment]
Second commit changes the output in my example to:
```
(
  level_0
  [level_1 "foo" "bar"]
  "baz"
)
```

Since the bracketed list contains no sub-lists (its elements are all atoms), it's printed on a single line.

**Comment by jd-boyd** [comment]
Thank you very much for your contribution. Let me look into why the tests failed. I think that `pretty_print` would be better than `format_tree`.

**Comment by mmmspatz** [comment]
I fixed the test failures (I don't think what's left is my fault), added a new test, and squashed.

**Comment by jd-boyd** [comment]
> I fixed the test failures (I don't think what's left is my fault), added a new test, and squashed.

Yep, I agree you aren't the cause of the remaining failures. Looks like the tox script needs updated by me. 

Thank you very much for your contribution.

**Comment by jd-boyd** [comment]
I've merged it.  Thank you again for your contribution.

**Pull request merged**
