### PR TITLE
Declare the license dynamic in pyproject.toml.

### PR DESCRIPTION
**Pull request by efokken-abb**
This should hopefully fix the corresponding setup failure named in #45

### CODE REVIEW

**Comment by jd-boyd** [comment]
I merged this, but can you explain why that was needed to fix the error?

**Comment by efokken-abb** [comment]
That‘s what the build error message said. Apparently it violates some pep standard to have something (like readme or license) be defined in the build process (so dynamically instead of predetermined) without it being declared dynamic in the pyproject.toml.
And some newer version of setuptools (or something else?) apparently now enforces that.
________________________________

**Comment by jd-boyd** [comment]
Thank you

**Comment by efokken-abb** [comment]
You're welcome! Any idea, when it will be updated on pypi?

**Pull request merged**
